import { toast } from "react-toastify";
import { sendEmail } from "../../lib/emailjs";


interface UniversityResponse {
  id: string;
  shortName: string;
  fullName: string;
  status: "active" | "inactive" | "pending";
  email: string;
  address?: string;
  phone?: string;
  maxStudents?: number;
  maxSupervisors?: number;
  description?: string;
  logoPath?: string;
}

interface UniAdminResponse {
  username: string; // Will be generated by backend
  fullName: string;
  email: string;
  phoneNumber?: string;
  role: "UniAdmin";
}

interface RegistrationResponse {
  message: string;
  university: UniversityResponse;
  admin: UniAdminResponse;
}

const API_BASE_URL =
  process.env.NEXT_PUBLIC_API_URL || "http://localhost:3000";

export function validateLogoFile(file: File): boolean {
  const maxSize = 2 * 1024 * 1024; // 2MB
  const allowedTypes = ["image/jpeg", "image/png", "image/gif"];

  if (file.size > maxSize) {
    toast.error("Logo must be less than 2MB");
    return false;
  }
  if (!allowedTypes.includes(file.type)) {
    toast.error("Please upload a valid image file (JPEG, PNG, or GIF)");
    return false;
  }
  return true;
}
export async function registerUniversity(
  formData: FormData
): Promise<RegistrationResponse> {
  try {
    console.log('🚀 Starting university registration...');
    const jsonData = Object.fromEntries(formData.entries());
    console.log('📝 Form data received:', Object.keys(jsonData));

    const requiredFields = [
      "shortName",
      "fullName", 
      "address",
      "email",
      "phone",
      "maxStudents",
      "maxSupervisors",
      "adminFullName",
      "adminEmail",
      "adminPhone",
      "adminPassword",
    ];

    const missingFields = requiredFields.filter((field) => !jsonData[field]);
    if (missingFields.length > 0) {
      throw new Error(`Missing required fields: ${missingFields.join(", ")}`);
    }

    console.log('📡 Sending registration request to backend...');

    const response = await fetch(
      `${API_BASE_URL}/api/admin/registerUniversity`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json",
          Authorization: `Bearer ${localStorage.getItem("authToken")}`,
        },
        body: JSON.stringify({
          shortName: (jsonData.shortName as string).toUpperCase(),
          fullName: jsonData.fullName,
          address: jsonData.address,
          email: jsonData.email,
          phone: jsonData.phone,
          maxStudents: parseInt(jsonData.maxStudents as string),
          maxSupervisors: parseInt(jsonData.maxSupervisors as string),
          adminFullName: jsonData.adminFullName,
          adminEmail: jsonData.adminEmail,
          adminPhone: jsonData.adminPhone,
          adminPassword: jsonData.adminPassword,
        }),
      }
    );

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      const errorMessage = errorData.message || errorData.details || `HTTP ${response.status}: ${response.statusText}`;
      console.error('❌ Backend registration failed:', errorMessage);
      throw new Error(errorMessage);
    }

    console.log('✅ Backend registration successful');
    const data = await response.json();
    
    if (!data.university || !data.admin || !data.admin.username) {
      throw new Error("Invalid response from server - missing required data");
    }

    console.log('📧 Registration successful, proceeding with email notification...');

    // Send welcome email via EmailJS
    try {
      console.log('📧 Preparing to send university registration email...');
      
      const templateParams = {
        to_name: jsonData.adminFullName as string,
        to_email: jsonData.adminEmail as string,
        username: data.admin.username,
        password: jsonData.adminPassword as string,
        university_name: data.university.shortName,
        university_code: data.university.shortName,
        admin_email: jsonData.adminEmail as string,
        login_url: `${window.location.origin}/auth/signin`,
        university_full_name: data.university.fullName,
        university_address: jsonData.address as string,
        university_phone: jsonData.phone as string,
        university_email: jsonData.email as string,
        max_students: jsonData.maxStudents as string,
        max_supervisors: jsonData.maxSupervisors as string,
        // Additional fields for EmailJS template
        user_role: 'University Administrator',
        contact_email: 'support@vision-fyp.com',
        year: new Date().getFullYear().toString()
      };

      const templateId = process.env.NEXT_PUBLIC_EMAILJS_UNIVERSITY_TEMPLATE || 
                        process.env.NEXT_PUBLIC_EMAILJS_USER_TEMPLATE || 
                        'template_ebbzvbb';
      
      console.log(`📧 Using template ID: ${templateId}`);

      await sendEmail({
        templateParams,
        templateId
      });

      console.log('✅ University registration email sent successfully');
      
    } catch (emailError) {
      console.error('❌ Failed to send registration email:', emailError);
      // Don't fail the registration if email fails
      toast.warning('University registered successfully, but welcome email could not be sent. Please check your email configuration.');
    }

    toast.success(
      `🎉 University "${data.university.shortName}" registered successfully! Admin username: ${data.admin.username}`
    );
    console.log('✅ University registration process completed');
    return data;
  } catch (error) {
    console.error('❌ University registration failed:', error);
    const message = error instanceof Error ? error.message : "Registration failed due to unknown error";
    toast.error(message);
    throw error;
  }
}
